### ISSUE TITLE
Add some additional content for Advanced Python

### ISSUE THREAD

**Issue by dmccreary** [CoderDojoTC/python#4]
Although we have lots of material for beginning Python, we don't have content for Advanced Python.  If you have ideas, please add them.

Here are some suggestions:

1. Debugging
2. Error handling
3. Logging
4. Graph Theory (pygraph, Networkx etc)
5. System Programming (pipes, threads, forks etc.)
6. NLP
7. Search (if-idf)
8. Data analysis - (data frames)
9. Notification - sending emails and text messages
10. Computer Vision - OpenCV

**Comment by parkererickson** [comment]
I am working on a MNIST handwritten digit notebook and lesson, as well as a stock analysis one. My linear regression baseball one can also be incorporated.
